src/screens/CauseForm/components/IconSelector/IconSelector.css
src/screens/CauseForm/components/IconSelector/index.js
src/screens/causeForm/index.js
src/styles/index.css
yarn.lock

See my latest commit for more details: https://github.com/Generosity-Market/Generosity-Market.github.io/commit/14a6c17c0db94cf100c5dcd98f217d48b48e78ae

Add IconSelector to CauseForm

---

public/api/causes.json
src/components/Banner/Banner.css
src/components/CauseTile/CauseTile.css
src/components/Heading/Heading.js
src/components/MainImage/MainImage.css
src/screens/CauseList/index.js
src/screens/Dashboard/components/UserCauses/UserCauses.css
src/screens/Organization/index.js
src/screens/Organization/organization.css
src/screens/SingleCause/SingleCause.css
src/screens/SingleCause/components/Tile/Tile.css
src/screens/SingleCause/components/TileSection/TileSection.css
src/screens/SingleCause/index.js
src/screens/dashboard/dashboard.css
src/screens/dashboard/index.js
src/styles/index.css

• Added two new CSS Variables --box-shadow --mini-box-shadow
• Tweaked styling to actionable elements and the MainImage component.
• Updated cause Tiles to show the donation amount if purchased.
• Created Heading component to replace all of the style H3's throughout the project.

Multiple Additions, see description

---

src/actions/actions.js
src/components/Banner/Banner.css
src/components/Banner/Banner.js
src/components/CauseTile/CauseTile.js
src/components/FontAwesome/FontAwesome.js
src/components/MainImage/MainImage.css
src/components/MainImage/MainImage.js
src/screens/CauseList/CauseList.js
src/screens/SingleCause/SingleCause.js
src/screens/SingleCause/components/DonorComments/DonorComments.js
src/screens/SingleCause/components/ProgressBar/ProgressBar.js
src/styles/index.css

- Includes showing the cause progress bar based on the actual current amount raised instead of a random number

Enhance performance on the single cause page by rendering placeholders for some components

---

package-lock.json
package.json
src/actions/actions.js
src/constants/linksData.js
src/containers/BaseLayout/baselayout.css
src/containers/StripeWrapper/StripeWrapper.js
src/index.js
src/reducers/reducer.js
src/routes/Routes.css
src/routes/Routes.js
src/screens/Checkout/Checkout.js
src/screens/Checkout/components/CheckoutForm/CheckoutForm.js
src/screens/Error404/Error404.js
src/screens/SingleCause/SingleCause.js
src/screens/SingleCause/components/TileSection/TileSection.js
src/screens/ThankYou/ThankYou.css
src/screens/ThankYou/ThankYou.js

-  Add the logic to determine if a tile is purchased or not.
- Create Thank You page, and redirect there upon successful donation.
- Add code splitting based on route
- Add fade in/out transitions to pages using react-transition-group

Include multiple updates, such as:

---

src/screens/Checkout/Checkout.css
src/screens/Checkout/Checkout.js
src/screens/Checkout/components/Cart/Cart.css
src/screens/Checkout/components/CartFooter/CartFooter.css
src/screens/Checkout/components/CartFooter/CartFooter.js
src/screens/Checkout/components/CheckoutForm/CheckoutForm.css
src/screens/Checkout/components/CheckoutForm/CheckoutForm.js

Redesign the checkout flow to fit new bottom navigation menu

---

src/components/Pill/Pill.css
src/components/Pill/Pill.js
src/screens/Dashboard/Dashboard.js
src/screens/Dashboard/components/DonorInfo/DonorInfo.css
src/screens/Dashboard/components/DonorInfo/DonorInfo.js
src/screens/Dashboard/components/Receipts/Receipts.js
src/screens/Dashboard/components/UserCauses/UserCauses.css
src/screens/Dashboard/components/UserCauses/UserCauses.js
src/utilities/utilities.js

Show Donations by other donors on the logged in users dashboard.

---

src/ducks/user/actions.js
src/ducks/user/index.js
src/ducks/user/operations.js
src/ducks/user/reducer.js
src/ducks/user/types.js
src/screens/Dashboard/Dashboard.js
src/screens/Dashboard/components/DonorInfo/DonorInfo.js
src/screens/Dashboard/components/Receipts/Receipts.js
src/screens/Dashboard/components/UserCauses/UserCauses.css
src/screens/Dashboard/components/UserCauses/UserCauses.js
src/services/services.js

Defer loading of a users causes and donations

---

package-lock.json
package.json

Also, updated package.json and package-lock.json to fix ability to run test suite
Fixes #109

Added jest-cli tools as a dependency

---

src/components/CauseTile/CauseTile.css
src/components/CauseTile/CauseTile.js
src/components/index.js
src/screens/CauseDetail/CauseDetail.js
src/screens/CauseDetail/components/AboutCause/AboutCause.js
src/screens/CauseDetail/components/DonorComments/DonorComments.js
src/screens/CauseDetail/components/TileSection/TileSection.js
src/screens/CauseForm/CauseForm.js
src/screens/CauseForm/components/IconSelector/IconSelector.js
src/screens/CauseList/CauseList.js
src/screens/CauseList/components/SliderSection/SliderSection.js
src/screens/Checkout/Checkout.js
src/screens/Checkout/components/Cart/Cart.js
src/screens/Checkout/components/CartFooter/CartFooter.js
src/screens/Checkout/components/CartItem/CartItem.js
src/screens/Checkout/components/CheckoutForm/CheckoutForm.js
src/screens/Checkout/components/EmptyCart/EmptyCart.js
src/screens/Dashboard/Dashboard.js
src/screens/Dashboard/components/DonorInfo/DonorInfo.js
src/screens/Dashboard/components/Receipts/Receipts.js
src/screens/Dashboard/components/UserCauses/UserCauses.js
src/screens/Dashboard/components/UserDetails/UserDetails.js
src/screens/NewOrgForm/NewOrgForm.js
src/screens/NewOrgForm/components/VerificationInputGroup/VerificationInputGroup.js
src/screens/Organization/Organization.js
src/screens/Organization/components/OrgCauses/OrgCauses.js
src/screens/Organization/components/OrgDetails/OrgDetails.js
src/screens/Splash/Splash.js
src/screens/ThankYou/ThankYou.js

Update shared component import/export pattern

---

src/components/Pill/Pill.js
src/components/ReceiptItem/ReceiptItem.css
src/components/ReceiptItem/ReceiptItem.js
src/components/index.js
src/screens/Dashboard/Dashboard.js
src/screens/Dashboard/components/DonorInfo/DonorInfo.js
src/screens/Dashboard/components/Receipts/Receipts.js

• Should also show the amount of any donations made to that cause

Dashboard should show what causes a user has previously supported

---

src/components/Tile/Tile.css
src/components/Tile/Tile.js
src/components/index.js
src/styles/index.css

• Should also show the amount of any donations made to that cause

Create Tile in shared UI Components

---

.eslintrc.json
package-lock.json
package.json

Add Husky and Eslint packages to project

---

src/components/containers/BaseLayout/components/SlideMenu/SlideMenu.js
src/components/containers/BaseLayout/components/TopMenu/TopMenu.js
src/components/containers/CauseDetail/DonationTile/DonationTile.js
src/components/containers/CauseDetail/TileSection/TileSection.js
src/components/containers/Checkout/Cart/Cart.js
src/components/containers/Checkout/CartItem/CartItem.js
src/components/containers/Checkout/CheckoutForm/CheckoutForm.js
src/components/containers/Checkout/EmptyCart/EmptyCart.js
src/ducks/cart/index.js
src/ducks/cart/operations.js
src/screens/src/CauseDetail.jsx
src/screens/src/Checkout.jsx
src/screens/src/ThankYou.jsx
src/store/store.js

Add cart to local storage to persist data

---

package-lock.json
package.json
src/actions/makeActionCreator.js
src/components/shared/src/HeadContainer.jsx
src/components/shared/tests/HeadContainer.spec.js
src/ducks/auth_token/reducer.js
src/ducks/cart/reducer.js
src/ducks/cause/reducer.js
src/ducks/organization/reducer.js
src/ducks/pageData/actions.js
src/ducks/pageData/index.js
src/ducks/pageData/reducer.js
src/ducks/pageData/types.js
src/ducks/user/reducer.js
src/index.jsx
src/reducers/reducer.js
src/screens/src/CauseDetail.jsx
src/screens/src/CauseList.jsx
src/screens/src/Organization.jsx
src/screens/src/Splash.jsx
src/screens/tests/CauseDetail.spec.js
src/store/initialState.js

using the web share api that's only available on mobile browsers
Fixes #65

Add mobile page sharing

---

src/screens/src/Login.jsx

Add better checks for location state

---

src/components/containers/Dashboard/UserDetails/UserDetails.js
src/ducks/user/operations.js

Fix name inputs

---

package-lock.json
package.json

add redux-devtools-extension to regular dependencies

---

package-lock.json
package.json

Move redux-promise to regular dependencies

---

src/ducks/pageData/reducer.js
src/screens/src/CauseDetail.jsx
src/screens/src/Login.jsx

Fix: Call navigator.share on share button click

---

src/screens/src/CauseDetail.jsx

fix: encode the url with the cause title for easier to read shared urls

---

src/components/containers/BaseLayout/BaseLayout.js

Add spacing

---

public/manifest.json

fix: Update start_url in manifest to test pwa routing

---

src/routes/ProtectedRoute.jsx
src/routes/RedirectRoute.jsx
src/routes/Routes.js
src/screens/src/CauseDetail.jsx
src/screens/src/Login.jsx
src/screens/src/Splash.jsx

fix: Redirect / and /login when already logged in

---

README.md
src/components/containers/Dashboard/Receipts/Receipts.js
src/components/containers/Dashboard/UserCauses/UserCauses.js
src/components/shared/src/CauseTile.jsx

fix: Add in view margin

---

public/manifest.json

Revert manifest.json > start_url changes

---

package-lock.json
package.json
src/components/containers/BaseLayout/components/BottomMenu/BottomMenu.css
src/components/containers/BaseLayout/components/BottomMenu/BottomMenu.js
src/components/containers/BaseLayout/components/BottomMenu/BottomMenu.spec.js
src/components/containers/BaseLayout/components/TopMenu/TopMenu.css
src/components/containers/BaseLayout/components/TopMenu/TopMenu.js
src/components/containers/Checkout/EmptyCart/EmptyCart.js
src/components/containers/Checkout/EmptyCart/EmptyCart.spec.js
src/constants/BottomNavLinks.js
src/constants/linksData.js

Cleanup dev components

---

src/components/containers/Checkout/CheckoutForm/CheckoutForm.css
src/components/containers/Checkout/CheckoutForm/CheckoutForm.js
src/screens/src/Checkout.jsx
src/screens/styles/Checkout.css

fix: Convert stripe slide-in panel to modal

---

src/components/containers/Checkout/CheckoutForm/CheckoutForm.css
src/components/containers/Checkout/CheckoutForm/CheckoutForm.js
src/components/containers/Dashboard/UserDetails/UserDetails.spec.js
src/components/shared/tests/AddressInputs.spec.js
src/components/shared/tests/DownloadCSV.spec.js
src/components/shared/tests/PhoneInput.spec.js
src/components/shared/tests/TextInput.spec.js

Cleanup test warnings

---

src/components/containers/Checkout/CheckoutForm/CheckoutForm.css

Quick fix checkout form

---

package-lock.json
package.json
src/components/containers/CauseDetail/QrModalContainer/QrModalContainer.css
src/components/containers/CauseDetail/QrModalContainer/QrModalContainer.js
src/components/containers/CauseDetail/QrModalContainer/QrModalContainer.test.js
src/components/containers/CauseDetail/QrModalContainer/index.js
src/components/containers/CauseDetail/index.js
src/components/containers/NewOrgForm/VerificationInputGroup/VerificationInputGroup.spec.js
src/components/shared/tests/InputGroup.spec.js
src/index.jsx
src/screens/src/CauseDetail.jsx
src/styles/index.css

- Please include a summary of the change. List any dependencies that are required for this change, if applicable.
- Include a screenshot/GIF if visual UI/UX changes.

Add qrcode generation
